# These are supported funding model platforms

github: # https://github.com/sovr610
patreon: # https://www.patreon.com/PBcoder
ko_fi: # https://ko-fi.com/pbcoder
issuehunt: # https://issuehunt.io/u/sovr610

